declare module 'virtual:runtime-embedded-assets' {
  export interface EmbeddedAssetEntry {
    readonly base64: string;
    readonly mimeType?: string;
  }

  export const embeddedAssets: Record<string, EmbeddedAssetEntry>;
}

/**
 * Side-effect module generated by the build: registers the optional Spine
 * runtime with `setSpineModuleLoader` when the project actually uses a
 * SpineSkeleton2D, and is empty otherwise (so exports that never touch Spine
 * ship none of it).
 */
declare module 'virtual:runtime-spine' {}
