declare module 'virtual:runtime-embedded-assets' {
  export interface EmbeddedAssetEntry {
    readonly base64: string;
    readonly mimeType?: string;
  }

  export const embeddedAssets: Record<string, EmbeddedAssetEntry>;
}

/**
 * Side-effect module generated by the build: registers the optional Spine
 * runtime with `setSpineModuleLoader` when the project actually uses a
 * SpineSkeleton2D, and is empty otherwise (so exports that never touch Spine
 * ship none of it).
 */
declare module 'virtual:runtime-spine' {}

/**
 * Side-effect module generated by the build: registers the `postprocessing`
 * module with `setPostprocessingModuleLoader` when the project actually places a
 * `PostProcess` node, and is empty otherwise. Without it a single-file export
 * cannot resolve the bare `import('postprocessing')` specifier at all — see
 * `PostProcessingPipeline.setPostprocessingModuleLoader`.
 */
declare module 'virtual:runtime-postprocessing' {}

/**
 * Generated by the build: wires the multiplayer `NetworkService` into the runner
 * when the project mentions networking anywhere, and is a no-op otherwise (so
 * single-player exports ship none of `src/net/**`).
 */
declare module 'virtual:runtime-network' {
  import type { SceneRunner } from '@pix3/runtime';

  export function installNetworkService(runner: SceneRunner): void;
}
